In [2]:
import pandas as pd
import numpy as np

features = pd.read_csv('../data/processed/features.csv')

In [4]:
features.head(5)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,visible_tower_count_5km,digital_elevation_model,region_enc,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,126.2,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,738
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,127.0,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,127.0,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,127.0,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,127.0,10.0,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714

In [5]:
features.columns

Index(['area', 'year', 'quarter', 'latitude', 'longitude', 'avg_d_mbps',
       'avg_u_mbps', 'avg_lat_ms', 'tests', 'nearest_tower_distance_km',
       'tower_count_1km', 'tower_count_2km', 'tower_count_5km',
       'visible_tower_count_5km', 'digital_elevation_model', 'region_enc',
       'typeOfArea_enc', 'city_enc', 'demand_growth_pct', 'region',
       'typeOfArea', 'city', 'block_number'],
      dtype='object')

In [9]:
#Adding a feature to get how many towers are concentrated very close to this location of all the towers that are around the area?

In [8]:
features['tower_density_ratio'] = features['tower_count_1km'] / (features['tower_count_5km'] + 1)

In [7]:
features['tower_density_ratio']

0       0.017297
1       0.014235
2       0.014235
3       0.014235
4       0.014235
          ...
6081    0.001597
6082    0.001597
6083    0.001597
6084    0.001597
6085    0.001597
Name: tower_density_ratio, Length: 6086, dtype: float64

In [11]:
# add speed ratio feature to measure the effeciency of upload and download speeds both together

In [12]:
features['speed_ratio'] = features['avg_u_mbps'] / (features['avg_d_mbps'] + 1)

In [13]:
features['speed_ratio']

0       0.186172
1       0.347437
2       0.403079
3       0.192584
4       0.182885
          ...
6081    0.387772
6082    0.148657
6083    0.138810
6084    0.110720
6085    0.105565
Name: speed_ratio, Length: 6086, dtype: float64

In [15]:
features.head(5)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,region_enc,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio,speed_ratio
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,738,0.017297,0.186172
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0.347437
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0.403079
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0.192584
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235,0.182885

In [39]:
features['speed_ratio'].idxmin()

3256

In [28]:
features['speed_ratio'][3256]

np.float64(0.004761771378952971)

In [32]:
features['avg_d_mbps'][3256]

np.float64(34.701)

In [33]:
features['avg_u_mbps'][3256]

np.float64(0.17)

In [34]:
features['speed_ratio'].idxmax()

956

In [35]:
features['speed_ratio'][956]

np.float64(4.108298498219539)

In [36]:
features['avg_d_mbps'][956]

np.float64(11.918)

In [37]:
features['avg_u_mbps'][956]

np.float64(53.071)

In [40]:
#drop the engineered feature as it is not accurate

In [42]:
features.columns

Index(['area', 'year', 'quarter', 'latitude', 'longitude', 'avg_d_mbps',
       'avg_u_mbps', 'avg_lat_ms', 'tests', 'nearest_tower_distance_km',
       'tower_count_1km', 'tower_count_2km', 'tower_count_5km',
       'visible_tower_count_5km', 'digital_elevation_model', 'region_enc',
       'typeOfArea_enc', 'city_enc', 'demand_growth_pct', 'region',
       'typeOfArea', 'city', 'block_number', 'tower_density_ratio',
       'speed_ratio'],
      dtype='object')

In [44]:
features.drop(columns= 'speed_ratio', inplace=True)

In [45]:
#average speeds per area

In [46]:
features = features.sort_values(['area', 'year', 'quarter'])

In [48]:
features.head(16)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,digital_elevation_model,region_enc,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,738,0.017297
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,10.0,2,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,10.0,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235
5,A'ali,2021,2,26.168586,50.516052,95.874667,19.979833,20.666667,63,0.949577,...,10.0,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235
6,A'ali,2021,3,26.168750,50.516785,60.233400,18.209600,19.200000,72,1.016811,...,10.0,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,740,0.011677
7,A'ali,2021,4,26.168468,50.517883,63.738000,23.130000,21.714286,78,1.090944,...,10.0,2,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.012442
8,A'ali,2022,1,26.168586,50.516052,100.830000,21.636000,18.833333,62,0.949577,...,10.0,2,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.014235
9,A'ali,2022,2,26.168750,50.514587,164.150000,20.926200,17.200000,55,0.854453,...,10.0,2,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204
10,A'ali,2022,3,26.168750,50.514587,144.339800,19.980400,21.200000,102,0.854453,...,10.0,2,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204
11,A'ali,2022,4,26.168750,50.514587,222.428400,24.865200,18.400000,94,0.854453,...,10.0,2,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204
12,A'ali,2023,1,26.168586,50.516052,233.595833,30.904000,26.166667,70,0.949577,...,10.0,2,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235
13,A'ali,2023,2,26.168750,50.514587,157.729200,27.537200,21.000000,49,0.854453,...,10.0,2,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.017204
14,A'ali,2023,3,26.168586,50.516052,218.762167,19.902167,16.833333,140,0.949577,...,10.0,2,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235
15,A'ali,2023,4,26.168586,50.516052,211.702667,23.157500,16.666667,94,0.949577,...,10.0,2,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235

In [51]:
features.tail(24)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,digital_elevation_model,region_enc,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio
6062,`Ayn ad Dar,2020,1,26.217055,50.534363,30.790,12.303,19.0,24,0.606966,...,10.0,0,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6063,`Ayn ad Dar,2020,2,26.217055,50.534363,34.234,12.250,21.0,48,0.606966,...,10.0,0,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6064,`Ayn ad Dar,2020,3,26.217055,50.534363,40.309,11.513,19.0,45,0.606966,...,10.0,0,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6065,`Ayn ad Dar,2020,4,26.217055,50.534363,67.038,13.745,17.0,42,0.606966,...,10.0,0,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6066,`Ayn ad Dar,2021,1,26.217055,50.534363,65.122,13.803,29.0,38,0.606966,...,10.0,0,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6067,`Ayn ad Dar,2021,2,26.217055,50.534363,58.497,10.250,16.0,24,0.606966,...,10.0,0,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6068,`Ayn ad Dar,2021,3,26.217055,50.534363,108.163,12.716,20.0,56,0.606966,...,10.0,0,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6069,`Ayn ad Dar,2021,4,26.217055,50.534363,90.197,19.312,16.0,51,0.606966,...,10.0,0,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6070,`Ayn ad Dar,2022,1,26.217055,50.534363,135.274,20.493,18.0,46,0.606966,...,10.0,0,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6071,`Ayn ad Dar,2022,2,26.217055,50.534363,80.814,17.899,19.0,39,0.606966,...,10.0,0,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6072,`Ayn ad Dar,2022,3,26.217055,50.534363,167.230,20.279,17.0,58,0.606966,...,10.0,0,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6073,`Ayn ad Dar,2022,4,26.217055,50.534363,193.554,17.300,18.0,27,0.606966,...,10.0,0,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6074,`Ayn ad Dar,2023,1,26.217055,50.534363,160.518,20.731,17.0,10,0.606966,...,10.0,0,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6075,`Ayn ad Dar,2023,2,26.217055,50.534363,210.112,22.805,46.0,11,0.606966,...,10.0,0,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6076,`Ayn ad Dar,2023,3,26.217055,50.534363,162.892,15.063,16.0,44,0.606966,...,10.0,0,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6077,`Ayn ad Dar,2023,4,26.217055,50.534363,115.764,15.478,17.0,21,0.606966,...,10.0,0,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6078,`Ayn ad Dar,2024,1,26.217055,50.534363,154.980,29.675,41.0,23,0.606966,...,10.0,0,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6079,`Ayn ad Dar,2024,2,26.217055,50.534363,296.439,35.614,15.0,16,0.606966,...,10.0,0,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6080,`Ayn ad Dar,2024,3,26.217055,50.534363,111.154,17.634,22.0,154,0.606966,...,10.0,0,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6081,`Ayn ad Dar,2024,4,26.217055,50.534363,69.348,27.279,20.0,12,0.606966,...,10.0,0,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6082,`Ayn ad Dar,2025,1,26.217055,50.534363,233.291,34.829,26.0,37,0.606966,...,10.0,0,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6083,`Ayn ad Dar,2025,2,26.217055,50.534363,199.800,27.873,18.0,37,0.606966,...,10.0,0,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6084,`Ayn ad Dar,2025,3,26.217055,50.534363,150.852,16.813,16.0,14,0.606966,...,10.0,0,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597
6085,`Ayn ad Dar,2025,4,26.217055,50.534363,302.518,32.041,15.0,12,0.606966,...,10.0,0,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597

In [83]:
features['area_rolling_d_mbps'] = (features.groupby('area')['avg_d_mbps'].transform(lambda x: x.shift(1)
    .rolling(2, min_periods=1).mean()).fillna(features['avg_d_mbps'].mean()))

In [85]:
features.drop(columns= 'city_rolling_d_mbps', inplace=True)

In [87]:
features.head(24)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio,year_trend,area_rolling_d_mbps
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,738,0.017297,0,152.420662
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0,34.608000
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0,29.696750
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,0,26.620417
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235,1,39.777750
5,A'ali,2021,2,26.168586,50.516052,95.874667,19.979833,20.666667,63,0.949577,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235,1,50.723833
6,A'ali,2021,3,26.168750,50.516785,60.233400,18.209600,19.200000,72,1.016811,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,740,0.011677,1,73.111083
7,A'ali,2021,4,26.168468,50.517883,63.738000,23.130000,21.714286,78,1.090944,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.012442,1,78.054033
8,A'ali,2022,1,26.168586,50.516052,100.830000,21.636000,18.833333,62,0.949577,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.014235,2,61.985700
9,A'ali,2022,2,26.168750,50.514587,164.150000,20.926200,17.200000,55,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,2,82.284000
10,A'ali,2022,3,26.168750,50.514587,144.339800,19.980400,21.200000,102,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,2,132.490000
11,A'ali,2022,4,26.168750,50.514587,222.428400,24.865200,18.400000,94,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,2,154.244900
12,A'ali,2023,1,26.168586,50.516052,233.595833,30.904000,26.166667,70,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,3,183.384100
13,A'ali,2023,2,26.168750,50.514587,157.729200,27.537200,21.000000,49,0.854453,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.017204,3,228.012117
14,A'ali,2023,3,26.168586,50.516052,218.762167,19.902167,16.833333,140,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,3,195.662517
15,A'ali,2023,4,26.168586,50.516052,211.702667,23.157500,16.666667,94,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,3,188.245683
16,A'ali,2024,1,26.168468,50.517883,239.182286,32.934857,25.714286,68,1.090944,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.012442,4,215.232417
17,A'ali,2024,2,26.168750,50.514587,201.196000,29.929000,16.000000,45,0.854453,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.017204,4,225.442476
18,A'ali,2024,3,26.168586,50.516052,193.565667,30.393500,21.833333,308,0.949577,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.014235,4,220.189143
19,A'ali,2024,4,26.168586,50.516052,211.633000,31.971333,20.166667,66,0.949577,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.014235,4,197.380833
20,A'ali,2025,1,26.168750,50.514587,343.471800,41.928400,17.000000,75,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,5,202.599333
21,A'ali,2025,2,26.168586,50.516052,232.462000,24.448667,17.000000,105,0.949577,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.014235,5,277.552400
22,A'ali,2025,3,26.168750,50.514587,303.261600,35.392000,15.200000,37,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,5,287.966900
23,A'ali,2025,4,26.168750,50.514587,293.912200,36.826000,15.800000,41,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,5,267.861800

In [88]:
features.tail(24)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio,year_trend,area_rolling_d_mbps
6062,`Ayn ad Dar,2020,1,26.217055,50.534363,30.790,12.303,19.0,24,0.606966,...,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,0,152.420662
6063,`Ayn ad Dar,2020,2,26.217055,50.534363,34.234,12.250,21.0,48,0.606966,...,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,0,30.790000
6064,`Ayn ad Dar,2020,3,26.217055,50.534363,40.309,11.513,19.0,45,0.606966,...,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,0,32.512000
6065,`Ayn ad Dar,2020,4,26.217055,50.534363,67.038,13.745,17.0,42,0.606966,...,4,144,0.000000,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,0,37.271500
6066,`Ayn ad Dar,2021,1,26.217055,50.534363,65.122,13.803,29.0,38,0.606966,...,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,1,53.673500
6067,`Ayn ad Dar,2021,2,26.217055,50.534363,58.497,10.250,16.0,24,0.606966,...,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,1,66.080000
6068,`Ayn ad Dar,2021,3,26.217055,50.534363,108.163,12.716,20.0,56,0.606966,...,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,1,61.809500
6069,`Ayn ad Dar,2021,4,26.217055,50.534363,90.197,19.312,16.0,51,0.606966,...,4,144,0.062893,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,1,83.330000
6070,`Ayn ad Dar,2022,1,26.217055,50.534363,135.274,20.493,18.0,46,0.606966,...,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,2,99.180000
6071,`Ayn ad Dar,2022,2,26.217055,50.534363,80.814,17.899,19.0,39,0.606966,...,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,2,112.735500
6072,`Ayn ad Dar,2022,3,26.217055,50.534363,167.230,20.279,17.0,58,0.606966,...,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,2,108.044000
6073,`Ayn ad Dar,2022,4,26.217055,50.534363,193.554,17.300,18.0,27,0.606966,...,4,144,0.005917,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,2,124.022000
6074,`Ayn ad Dar,2023,1,26.217055,50.534363,160.518,20.731,17.0,10,0.606966,...,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,3,180.392000
6075,`Ayn ad Dar,2023,2,26.217055,50.534363,210.112,22.805,46.0,11,0.606966,...,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,3,177.036000
6076,`Ayn ad Dar,2023,3,26.217055,50.534363,162.892,15.063,16.0,44,0.606966,...,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,3,185.315000
6077,`Ayn ad Dar,2023,4,26.217055,50.534363,115.764,15.478,17.0,21,0.606966,...,4,144,-0.494118,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,3,186.502000
6078,`Ayn ad Dar,2024,1,26.217055,50.534363,154.980,29.675,41.0,23,0.606966,...,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,4,139.328000
6079,`Ayn ad Dar,2024,2,26.217055,50.534363,296.439,35.614,15.0,16,0.606966,...,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,4,135.372000
6080,`Ayn ad Dar,2024,3,26.217055,50.534363,111.154,17.634,22.0,154,0.606966,...,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,4,225.709500
6081,`Ayn ad Dar,2024,4,26.217055,50.534363,69.348,27.279,20.0,12,0.606966,...,4,144,1.383721,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,4,203.796500
6082,`Ayn ad Dar,2025,1,26.217055,50.534363,233.291,34.829,26.0,37,0.606966,...,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,5,90.251000
6083,`Ayn ad Dar,2025,2,26.217055,50.534363,199.800,27.873,18.0,37,0.606966,...,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,5,151.319500
6084,`Ayn ad Dar,2025,3,26.217055,50.534363,150.852,16.813,16.0,14,0.606966,...,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,5,216.545500
6085,`Ayn ad Dar,2025,4,26.217055,50.534363,302.518,32.041,15.0,12,0.606966,...,4,144,-0.512195,Capital Governorate,PPL,`Ayn ad Dar,425,0.001597,5,175.326000

In [66]:
# Year trend calculation for the model to know what year specifically the record is token from, fro more effecient detection of network improvements over the years

In [67]:
features['year_trend'] = features['year'] - features['year'].min()

In [70]:
features.head(24)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,typeOfArea_enc,city_enc,demand_growth_pct,region,typeOfArea,city,block_number,tower_density_ratio,city_rolling_d_mbps,year_trend
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,738,0.017297,152.420662,0
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,34.608000,0
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,29.696750,0
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,5,0,0.000000,Northern Governorate,PPLX,A'ali,714,0.014235,26.620417,0
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235,39.777750,1
5,A'ali,2021,2,26.168586,50.516052,95.874667,19.979833,20.666667,63,0.949577,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.014235,50.723833,1
6,A'ali,2021,3,26.168750,50.516785,60.233400,18.209600,19.200000,72,1.016811,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,740,0.011677,73.111083,1
7,A'ali,2021,4,26.168468,50.517883,63.738000,23.130000,21.714286,78,1.090944,...,5,0,-0.199454,Northern Governorate,PPLX,A'ali,714,0.012442,78.054033,1
8,A'ali,2022,1,26.168586,50.516052,100.830000,21.636000,18.833333,62,0.949577,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.014235,61.985700,2
9,A'ali,2022,2,26.168750,50.514587,164.150000,20.926200,17.200000,55,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,82.284000,2
10,A'ali,2022,3,26.168750,50.514587,144.339800,19.980400,21.200000,102,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,132.490000,2
11,A'ali,2022,4,26.168750,50.514587,222.428400,24.865200,18.400000,94,0.854453,...,5,0,0.068259,Northern Governorate,PPLX,A'ali,714,0.017204,154.244900,2
12,A'ali,2023,1,26.168586,50.516052,233.595833,30.904000,26.166667,70,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,183.384100,3
13,A'ali,2023,2,26.168750,50.514587,157.729200,27.537200,21.000000,49,0.854453,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.017204,228.012117,3
14,A'ali,2023,3,26.168586,50.516052,218.762167,19.902167,16.833333,140,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,195.662517,3
15,A'ali,2023,4,26.168586,50.516052,211.702667,23.157500,16.666667,94,0.949577,...,5,0,0.127796,Northern Governorate,PPLX,A'ali,714,0.014235,188.245683,3
16,A'ali,2024,1,26.168468,50.517883,239.182286,32.934857,25.714286,68,1.090944,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.012442,215.232417,4
17,A'ali,2024,2,26.168750,50.514587,201.196000,29.929000,16.000000,45,0.854453,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.017204,225.442476,4
18,A'ali,2024,3,26.168586,50.516052,193.565667,30.393500,21.833333,308,0.949577,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.014235,220.189143,4
19,A'ali,2024,4,26.168586,50.516052,211.633000,31.971333,20.166667,66,0.949577,...,5,0,0.379603,Northern Governorate,PPLX,A'ali,714,0.014235,197.380833,4
20,A'ali,2025,1,26.168750,50.514587,343.471800,41.928400,17.000000,75,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,202.599333,5
21,A'ali,2025,2,26.168586,50.516052,232.462000,24.448667,17.000000,105,0.949577,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.014235,277.552400,5
22,A'ali,2025,3,26.168750,50.514587,303.261600,35.392000,15.200000,37,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,287.966900,5
23,A'ali,2025,4,26.168750,50.514587,293.912200,36.826000,15.800000,41,0.854453,...,5,0,-0.470226,Northern Governorate,PPLX,A'ali,714,0.017204,267.861800,5

In [71]:
features.to_csv('../data/processed/features_engineered.csv', index=False)

In [73]:
features.shape

(6086, 26)

In [79]:
features['avg_d_mbps'].max()

np.float64(1330.731)

In [80]:
features['avg_d_mbps'].min()

np.float64(0.349)

In [81]:
features['avg_d_mbps'].mean()

np.float64(152.42066227997978)

In [82]:
features['avg_d_mbps'].median()

np.float64(131.25038461538463)

In [89]:
area_stats = features.groupby('area').agg(
    area_median_d   = ('avg_d_mbps', 'median'),
    area_median_u   = ('avg_u_mbps', 'median'),
    area_median_lat = ('avg_lat_ms', 'median'),
    area_test_count = ('tests', 'sum')
).reset_index()

In [97]:
area_stats

,area,area_median_d,area_median_u,area_median_lat,area_test_count
0,A'ali,178.857833,23.143750,20.416667,2070
1,Abu Baham,116.483250,15.609750,19.000000,1210
2,Abu Saiba,218.921875,25.252250,18.625000,2630
3,Abu Saybi`,144.211833,20.025333,20.000000,2150
4,Ad Dayr,155.474375,17.554875,18.000000,2751
...,...,...,...,...,...
268,`Ali,190.516322,25.560121,19.929167,10941
269,`Arad,245.188900,33.963600,17.800000,4096
270,`Askar,161.545363,22.310025,17.922078,1729
271,`Awali,171.088421,20.330940,19.970280,1880
272,`Ayn ad Dar,125.519000,17.766500,18.000000,889

In [101]:
area_stats.dtypes

area                object
area_median_d      float64
area_median_u      float64
area_median_lat    float64
area_test_count      int64
dtype: object

In [102]:
area_stats.max()

area               `Ayn ad Dar
area_median_d          266.178
area_median_u          37.8555
area_median_lat          142.0
area_test_count          25362
dtype: object

In [103]:
area_stats['area_median_d'].max()

np.float64(266.178)

In [108]:
area_stats.tail(50)

,area,area_median_d,area_median_u,area_median_lat,area_test_count
223,Ramee Grand Htl & Spa,223.810000,30.896500,23.500000,2142
224,Ramee International,204.312000,31.536500,26.500000,2214
225,Ramee Palace Hotel All Suites Hotel,139.203500,28.174000,17.000000,309
226,Ramee Suites 3 Apartment,74.049000,14.815500,15.000000,32
227,Rameee Suite 3,158.384500,24.350000,19.000000,511
228,Residence Inn By Marriott,131.300500,20.827000,18.500000,1009
229,Royal Phoenicia,185.540000,25.773000,22.500000,1759
230,SHERATON BAHRAIN HTL AND TOWER,161.025000,23.404000,20.000000,1508
231,Sadad,145.497267,17.826282,18.361111,2701
232,Safirah,128.971882,17.776654,18.590909,2956
233,Salmabad,148.461220,23.043400,19.285714,7076
234,Samahij,140.800500,16.892700,19.500000,2912
235,Sanabis,147.763500,22.864250,18.250000,1798
236,Sanad,203.423338,22.319741,18.757310,12842
237,Sar,209.258941,23.122125,19.564706,6950
238,Sea Shell,210.132750,27.002000,18.250000,1882
239,Sealoft Boutique Chalets,140.454000,24.873500,15.750000,296
240,Shahrakkan,132.283253,18.971448,19.215909,5477
241,Sheraton Bahrain Hotel,134.707500,24.914500,23.000000,3002
242,Sitrah,159.103087,22.298714,19.603896,2198
243,Sofitel Bahrain Zallaq Thalass,33.278000,10.760000,16.000000,1
244,Sofitel Bahrain Zallaq Thalassa Sea And Spa,190.677125,26.033300,21.500000,582
245,Sofitel Bahrain Zallaq Thalassa Sea and Spa Hotel,263.865000,29.227500,16.000000,1541
246,Somerset Al Fateh Bahrain,145.165500,23.608000,28.500000,1819
247,Sufalah,60.013362,9.161825,23.205556,3021
248,Tashshan,151.797750,22.165250,19.500000,2606
249,The Domain Bahrain,192.403500,32.217000,29.000000,2603
250,The Dragon & Sealoft Resort,81.271250,12.819000,24.250000,1421
251,The Dragon Beach Hotel & Resort,98.508000,16.494625,24.833333,862
252,The Gulf Hotel Bahrain,162.182000,26.435500,32.500000,973
253,The Palace Boutique,200.291000,28.960000,16.500000,1078
254,The Ritz Carlton Bah,133.782500,17.538000,20.000000,144
255,The Westin Bahrain City Centre,204.761500,37.855500,27.000000,5679
256,Tubli,200.568000,21.274333,21.000000,2489
257,Tulip Inn Bahrain Suites And Residence,151.838500,31.847000,18.000000,1100
258,Tylos,166.474250,25.254250,19.000000,4680
259,Umm Jidr,110.475917,15.176500,21.250000,201
260,Umm Kharurah,27.164500,3.958500,21.500000,3
261,Umm al Hassam,212.762667,30.292167,19.666667,4109
262,Umm an Na'san,76.000000,22.043500,26.250000,213
263,Umm ash Sha`um,190.354000,21.112000,19.500000,1040
264,Umm ash Shajar,85.842584,12.899032,30.000000,3720
265,V Tower Residence,147.233500,21.523500,21.000000,4223
266,Wadiyan,165.277500,19.605667,17.500000,2109
267,Zalaqat as Sufun,87.064500,10.863000,24.500000,50
268,`Ali,190.516322,25.560121,19.929167,10941
269,`Arad,245.188900,33.963600,17.800000,4096
270,`Askar,161.545363,22.310025,17.922078,1729
271,`Awali,171.088421,20.330940,19.970280,1880
272,`Ayn ad Dar,125.519000,17.766500,18.000000,889

In [109]:
features = features.merge(area_stats, on='area', how='left')

In [112]:
features['distance_x_density'] = (
    features['nearest_tower_distance_km'] * 
    (1 / (features['tower_count_5km'] + 1))
)

In [113]:
features.head(5)

,area,year,quarter,latitude,longitude,avg_d_mbps,avg_u_mbps,avg_lat_ms,tests,nearest_tower_distance_km,...,city,block_number,tower_density_ratio,year_trend,area_rolling_d_mbps,area_median_d,area_median_u,area_median_lat,area_test_count,distance_x_density
0,A'ali,2020,1,26.167764,50.516785,34.608000,6.629200,21.200000,52,0.910574,...,A'ali,738,0.017297,0,152.420662,178.857833,23.14375,20.416667,2070,0.004922
1,A'ali,2020,2,26.168586,50.516052,24.785500,8.958833,23.166667,105,0.949577,...,A'ali,714,0.014235,0,34.608000,178.857833,23.14375,20.416667,2070,0.005069
2,A'ali,2020,3,26.168586,50.516052,28.455333,11.872833,25.000000,72,0.949577,...,A'ali,714,0.014235,0,29.696750,178.857833,23.14375,20.416667,2070,0.005069
3,A'ali,2020,4,26.168586,50.516052,51.100167,10.033667,26.833333,137,0.949577,...,A'ali,714,0.014235,0,26.620417,178.857833,23.14375,20.416667,2070,0.005069
4,A'ali,2021,1,26.168586,50.516052,50.347500,9.390667,44.500000,80,0.949577,...,A'ali,714,0.014235,1,39.777750,178.857833,23.14375,20.416667,2070,0.005069

In [114]:
features.to_csv('../data/processed/features_engineered.csv', index=False)

In [117]:
features['tower_count_5km']

0       184.000000
1       186.333333
2       186.333333
3       186.333333
4       186.333333
           ...
6081    625.000000
6082    625.000000
6083    625.000000
6084    625.000000
6085    625.000000
Name: tower_count_5km, Length: 6086, dtype: float64